# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181218_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
    ]
