# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-18 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181218_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dislike_id',
            field=models.TextField(blank=True, default='0 ', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_id',
            field=models.TextField(blank=True, default='0 ', null=True),
        ),
    ]
